CC=g++

all: compile_main

compile_main:
	@$(CC) -c main.cpp
	@$(CC) -o main.bin main.o


compile_fuerzabruta:
	@$(CC) -c fuerzabruta.cpp
	@$(CC) -o fuerzabruta.bin fuerzabruta.o


clean:
	rm -rf *.o *.bin